language: python
python:
  - 2.7
  - 3.8
env:
  - FILENAME=test-eslint1
  - FILENAME=test-eslint2
  - FILENAME=test-eslint3
  - FILENAME=test
  - FILENAME=test2
  - FILENAME=test3
  - FILENAME=test-bailout
install: pip install flake8 junit-xml yamlish
before_script: flake8 . --max-line-length=88
script:
  - python tap2junit/tap13.py
  - python -m tap2junit -i test/fixtures/${FILENAME}.tap -o test/output/${FILENAME}.xml
  - cat test/output/${FILENAME}.xml
