name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive .
      - run: black --check .
      - run: codespell --quiet-level=2 --skip="*.tap"  # --ignore-words-list="" 
      - run: flake8 . --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install junit_xml yamlish
      - run: mypy --ignore-missing-imports .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
      - run: |
          for FILENAME in "test-eslint1 test-eslint2 test-eslint3 test test2 test3"; do
            echo "Testing $FILENAME..."
            python tap2junit/tap13.py
            python -m tap2junit -i "test/fixtures/$FILENAME}.tap" -o "test/output/$FILENAME.xml"
            cat "test/output/$FILENAME.xml"
          done
